[package]
name = "rsmad"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[build-dependencies]
bindgen = "0.70.0"

[dependencies]
byteorder = "1.5.0"
thiserror = "1.0.61"
libc = "0.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0"